// Home
export const BEGIN_GET_GIFS_TRENDING_GIFS = 'BEGIN_GET_GIFS_TRENDING_GIFS';
export const SUCCESS_GET_GIFS_TRENDING_GIFS = 'SUCCESS_GET_GIFS_TRENDING_GIFS';
export const ERROR_GET_GIFS_TRENDING_GIFS = 'ERROR_GET_GIFS_TRENDING_GIFS';
